version: "3.8"

services:
  localstack:
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:8080:4566"
    environment:
      - SERVICE=Lambda
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
