service: bankslipservice
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  bankSlipService:
    handler: index.bankSlipService
    events:
      - http:
          path: /boleto/{digitableLine}
          method: GET
          parameters:
              paths:
                digitableLine: true
