service: bankslipservice
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  bankSlipService:
    handler: handler.bankSlipService
  events:
   - http:
       path: /boleto/
       method: GET
